python train.py -m "ICModel" -d "./Dataset/BreastEW_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/Tic-tac-toe_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/Australia_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/german.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/German_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/Hillvalley_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/SpectEW_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/Madelon_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/SonarEW_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/IonosphereEW_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/heart297.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/Vote_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/Exactly_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/Musk_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/CongressEW_data.mat" --hidden_size 32 --DNM_M 20 -n 10
python train.py -m "ICModel" -d "./Dataset/KrVsKpEW_data.mat" --hidden_size 32 --DNM_M 20 -n 10
